### ISSUE TITLE
new-new-new Service worker not registering

### ISSUE THREAD

**Issue by shotlom** [choojs/bankai#245]
After a ```choojs/bankai#new-new-new build```, in which the ``` app.use(require('choo-service-worker')())``` is uncommented and ```set NODE_ENV=production```, the service worker does not register.

I can confirm however that the bundle.js file built by bankai does have

```
navigator.serviceWorker.register
```

If I register the serviceWorker in the index.html, rather than bundle.js then the serviceWorker registers.

**Comment by YerkoPalma** [comment]
I guess that this is because the `choo-service-worker` module register the `/sw.js` path if no name is passed. And bankai now build the bundle inside a folder, so I think it tries to register `/<some_uid>/sw.js`.
To probe if this is the reason of your issue, try to register the service worker like `app.use(require('choo-service-worker')('../sw.js'))` and tell me if that make any change.

**Comment by shotlom** [comment]
Yep, that seems to work! Brilliant!

**Comment by tnguyen14** [comment]
It looks like bankai is outputting the service worker file as `service-worker.js`, and not `sw.js`, is that correct?

**Comment by goto-bus-stop** [comment]
Oh yeah; if your service worker source file is called `service-worker.js` you need to do `require('choo-service-worker')('/service-worker.js')` instead

**Comment by tnguyen14** [comment]
Do you know why bankai output an empty `service-worker.js` by default? Is there a way to configure it to use the `sw.js` that comes with `choo-service-worker`?

**Comment by goto-bus-stop** [comment]
the technical reason is that if no service worker file is found, bankai uses an empty Buffer instead as the input for the service worker node in the graph it uses to build things. But we could add a check in `lib/cmd-build.js` so that empty service worker files are not written

bankai looks for `sw.js` and `service-worker.js` files in your own source and uses whichever it finds first. If you want to use some service worker implementation from npm you can create a local service worker file that only requires the one from npm:

```js
// sw.js
require('choo-service-worker/sw')
```

AFAIK the sw.js in choo-service-worker is only an example and not intended to be used in this way though

**Comment by tnguyen14** [comment]
Ah I see. That is very good to know.

I agree that if there's no service worker, the builder should not write the file. Though that could cause a 404 in the browser network if the default `create-choo-app` registers a service worker, right?

**Comment by tnguyen14** [comment]
Also, can this be documented for bankai?

> bankai looks for `sw.js` and `service-worker.js` files in your own source and uses whichever it finds first.
