### ISSUE TITLE
Routes with params not working with bankai start

### ISSUE THREAD

**Issue by Flet** [choojs/bankai#281]
When looking at #273, I also noticed that params do not work with `bankai start`:

Example:
```js
app.route('/asd/:foo', require('./views/main'))
```

```bash
GET /asd/123
# No route found for /asd/123
``

**Comment by yoshuawuyts** [comment]
Hmmm, there's 2 constraints here:

- We can't server render wildcard routes in `bankai build` because they don't resolve to a specific path, which means that they'd be super weird files on disk — and would require all sorts of workarounds to get to render right on the server (e.g. `choo` apps can no longer assume `state.params` to exist, etc. etc.)
- We should resolve routes in `bankai start`, so they can be loaded with the right data and server rendered.

I feel that using JIT server rendering might be a solution for this. If we expect `bankai/http` to run in production behind a CDN, it might be good to make use of a (persistent) LRU cache for the files, but compile the files as they come in. Also make sure to invalidate the cache when any of the file watchers trigger.

Does this make sense?
