### ISSUE TITLE
Allow setting the base path for the application

### ISSUE THREAD

**Issue by Flet** [choojs/bankai#309]
Currently, `graph-document.js` sets all URLs to bundles as `/`, which means the application must be deployed to the root of a site in order to work.

Allowing a user to override this would ensure applications can be deployed to a subdirectory on a domain without issue (i.e. http://example.com/mychooapp/is/way/down/here).

Unfortunately there is not a way to get around this without modifying the generated HTML files after `bankai` runs.

**Comment by finnp** [comment]
Also routers are confused because of this. In development mode they should be able to server `/` from `localhost`, but in production it could be `/berlin` as root for example.

Furthermore when the static routes are created, it should ignore the "root path".

I think a solution could be to somehow pass `{"root": "/berlin"}` to bankai.

Then when building dist it will will NOT put files in a subdirectory `/berlin`, but the referenced paths are prefixed with `/berlin`.

Also it would set `process.env.ROOT_PATH` to `/berlin`, so it can be passed to routers in the frontend (for normal `npm start` this would be `''`).

**Comment by goto-bus-stop** [comment]
#399
