### ISSUE TITLE
Having a large amount of divs slows bundling by a lot

### ISSUE THREAD

**Issue by nicknikolov** [choojs/bankai#337]
example code in my view after I create choo app with `create-choo-app` module:
```
  function weeks () {
    var divs = []
    for (var i = 0; i < 4000; i++) {'
      var week = html`<div class= dib w1 bg-yellow">
        ${i}
      </div>`
      divs.push(week)
    }

    return divs
  }

  return html`
    <body class="bg-washed-yellow">
      <div class="ph3 f0">
        ${weeks()}
      </div>
    </body>
  `
```
this takes several seconds to bundle, completely kills live-reload workflow.

**Comment by nicknikolov** [comment]
in fact, maybe the correct thing to say is that SSR takes a lot of time not bunding:
@goto-bus-stop please correct me

**Comment by goto-bus-stop** [comment]
yep we dug into this on IRC and the problem is that, when SSR generates a lot of html, the documentify pipeline takes a very long time to process it. that's because bankai adds about 10 transforms that each parse the full html file to add a few small things.

two ideas that may help fix:

 - collapsing transforms, adding all bankai's tags in a single hyperstream pass
 - inserting the SSR'd html somewhere near the end of the pipeline using a new transform, so that only `post` transforms will run on it (once that lands in documentify), and not bankai's document setup transforms.

**Comment by bjrnt** [comment]
Is there anything that the end-user can currently do to alleviate this? I'm currently experiencing the same issue. Is there any way to turn of SSR for development builds?

**Comment by goto-bus-stop** [comment]
One workaround is to go into node_modules/bankai/lib/graph-document.js, and replace the line `var body = res.body` with `var body = "`. Not ideal :(

**Comment by goto-bus-stop** [comment]
8eab621 helps, but not enough!

**Comment by nicknikolov** [comment]
I reckon we should keep this issue open as a general UX issue?

**Comment by yoshuawuyts** [comment]
@nicknikolov yeah, probably (:

**Comment by goto-bus-stop** [comment]
hstream helped a lot I think. of course it's always good to be faster but I think it is not terrible anymore. do you reckon this can be closed?

**Comment by nicknikolov** [comment]
I've moved on from that project so can't test currently. So i'm gonna close it, if it comes up again for me i might reopen. Thanks for the help on that issue!
