### ISSUE TITLE
Add a --no-babelify switch

### ISSUE THREAD

**Issue by toddself** [choojs/bankai#348]
As noted in #341, if we are running babelify globally, any package which uses babelify in it's build process but does not include the babel packages in it's `dependencies` list (since the package's published version is a pre-built bundle), will cause Bankai to fail.

The only way to discover this issue is to try to build something, if the offending package is the dependency of a dependency it gets even harder to figure out.  If it is expecting multiple presets or babel packages, each one has to be discovered independently (the stacktrace is only moderately helpful).

Also, as with the case for [diff](https://github.com/kpdecker/jsdiff), the version of babel/babelify is incompatible with the version used for building the library, so even installing the required babel packages in the top-level project causes the build to fail since the packages do not run under the babel runtime provided.

This means it is currently impossible to build a project which relies on jsdiff using bankai (or any other package which exhibits similar attributes).

Ergo, we need to provide some ability to tell bankai to _not_ run babelify globally (or at all) or we need to turn off the reading of custom `.babelrc` configurations.

We've discussed the latter of these options and that's I think an even more worse scenario than the first one.

I know the idea is to have a zero-configuration tool, but the problem here is that babel _requires_ configuration; it is impossible to use it without configuration, and it's configuration is definitely not a one-size-fits-all type of thing (or the tool itself would be infinitely less configurable).

**Comment by yoshuawuyts** [comment]
Hey, thanks for the issue. Can I please stress that one of the primary goals of Bankai is to not introduce any configuration. I don't agree with the line of reasoning in the last paragraph, and reject the premise that because something lower-level has configuration, we should also have configuration. Programming is a game of tradeoffs, and it's up to us to find the right ones for Bankai.

I think we should definitely talk about what the best approach is on how to combine Bankai & Babel, but pushing for command line flags is counter-productive. If we are going to have this discussion, we should not go down the route of flags as the first solution to every problem.

To be frank, I'm getting a little tired (an possibly frustrated) with the interactions we've been having recently. I know we approach problems from different angles (which is great!), but it feels that our interactions have had aggressive undertones. Whether it is about performance, SSR, or configuration. It feels that there's a push to do things a particular way, but with few regards of the constraints surrounding it.

I don't know if this is just me, but I feel it's worth bringing up that it is stressing me out. To the point where my first reaction to this issue was: _"nope, closing this — I'm not engaging in another argument about introducing flags."_ But that doesn't seem constructive, so I'm hoping that by explaining how I'm feeling we might resolve things differently.

Before I close this out, I want to emphasize that by no means I want to dismiss the issues you're experiencing. I get that we're in a tough spot right now with regards to Babel. We should strive to find a great solution. But in doing so, show kindness & understanding of our mutual goals.

I hope this all makes sense, and thank you!

**Comment by goto-bus-stop** [comment]
it seems tough to fix our babel difficulties without introducing breaking changes.

i wonder if it would be possible to add two babelify transforms. one that runs on files in node_modules, that has the `babelrc: false` option and only includes preset-env, that would not read .babelrc files in dependency source code; and another that runs on local files, that includes preset-env and merges in the user's babelrc files, like it does now. we could do something like that in a patch release, i think.

**Comment by goto-bus-stop** [comment]
closing per #352!
