### ISSUE TITLE
question: proxy to api server in development server mode

### ISSUE THREAD

**Issue by cdaringe** [choojs/bankai#398]
# problem

- i have a REST api and want trusted, same origin requests satisfied from my choo UI app to and from the api

# discussion

recipe is partially discussed here: https://github.com/choojs/bankai#http, but not abundantly clear how to facilitate this.  create-react-app passes the package.json's "proxy" field into webpack's express server and sends certain unsatisfied requests to the proxy.

tips would be great! i'd PR doc updates if we wanted to prescribe a quasi-formal recipe

**Comment by yoshuawuyts** [comment]
@cdaringe the idea is that instead of having a "proxy" server, Bankai can run inside the same process as your API server. So by following the `http` instructions, you can hook up a regular HTTP server with Bankai.

Alternatively there's also https://github.com/fastify/fastify-bankai, which interacts with Bankai directly (:

**Comment by cdaringe** [comment]
thanks :)
