### ISSUE TITLE
expose mime types in core API

### ISSUE THREAD

**Issue by yoshuawuyts** [choojs/bankai#402]
Right now our core API only outputs the `data.buffer` and `data.hash` properties. It'd be real neat if we also exposed `data.mime` or something similar.

Turns out our `./http.js` API isn't flexible enough for e.g. `fastify`, so making it easier for them to integrate would be :100:

**Comment by goto-bus-stop** [comment]
Would it make sense to add a third parameter in buffer-graph to the `createEdge` function, so that we can specify any custom metadata to store on the node?

```js
createEdge('bundle', stylesBuffer, {
  mime: 'text/css'
})
// graph.data.styles.bundle is now { data, hash, mime }
```

We could also use that to get rid of some of the hackiness where we store lists of file names in buffers, by doing this:

```js
createEdge('bundle', mainBundleBuffer, {
  mime: 'application/javascript',
  dynamicBundles: dynamicBundleNames
})
// graph.data.scripts.bundle is now { data, hash, mime, dynamicBundles }
```

(instead of `createEdge('scripts', 'list', Buffer.from(dynamicBundleNames).join(','))`)

**Comment by yoshuawuyts** [comment]
actually: yeah probably!
