### ISSUE TITLE
Bankai Build with yo-yo/bel

### ISSUE THREAD

**Issue by earthtone** [choojs/bankai#404]
I may be missing something fundamental here, so please bear with me. 

Is it possible to use the `bankai build` command to compile a file that uses something lower level than choo, like yo-yo/bel or even just the browser's DOM API. Even without checking for `window`, choo apps compile fine for me with `bankai build`, but nothing else seems to work as I'd expect it to. 

For example, the following example renders properly when using `bankai start` and compiles without errors using `bankai build`, but does not render when served over a static server.

```
var html = require('yo-yo');

var $header = function() {
	return html` <header>
		<nav class="navbar">
			<a href="/" onclick=${linkHandler}>Home</a>
			<a href="/about" onclick=${linkHandler}>About</a>
		</nav>
	</header>`;

	function linkHandler(e) {
		e.preventDefault();
		console.log('link clicked', e.target.href);
		router.emit(e.target.href);
	}
};

if (typeof window !== 'undefined' && !module.parent) {
	window.addEventListener('load', function() {
		document.body.appendChild($header());
	});
}
```

Similarly, using the DOM API doesn't seem to work either.

```
if(type window !== 'undefiend' && !module.parent){
  var el = document.creatElement('h1');
  el.textContent = 'Hello World';
  document.body.appendChild(el);
}
```

Am I missing a transform or something? I know there has to be something I'm just not understanding properly about the way Bankai is supposed to work. Any information to help point me in the right direction would be greatly appreciated.

**Comment by goto-bus-stop** [comment]
Thanks for reporting! My first intuition is that [browser-pack-flat](https://github.com/goto-bus-stop/browser-pack-flat) may be handling `module.parent` incorrectly. It's supposed to compile it to something meaningful but that part has not been tested very extensively. browser-pack-flat is only used in optimised builds using `bankai build`, so that would explain the difference.

**Comment by bendik** [comment]
sloppy reply, but giving you a take: 

the only place it is “safe” to use raw dom api’s is generally in the DOMCONTENTLOADED and store events, since events should generally only trigger when interactions happen and not when node is trying to server render. but manipulating your view from your store is not a reccommended choo workflow. it is possible to read from your view dom in your state callback, but try to wrap those event functions inside your view. 

if you want to write to the dom bel does return actual dom nodes when running in the browser, but to leverage server rendering capabilities its best to stick to only using bels apis for creating your view and not manipulating them further. it currently defaults to overwrite anything in the body element so manipulating it outside of any route mounted view function will be overwritten in the next ‘render’ event due to dom diffing pragma. all view functions should return html’’ and be nested, generally. if you need to set innerHTML of a node i recommend returning something called by ‘bel/raw’

hope it was somewhat helpful

**Comment by goto-bus-stop** [comment]
Hmm, I'm having trouble reproducing this—would it be possible for you to share a small example project?

**Comment by earthtone** [comment]
@goto-bus-stop Sorry for the delay in getting this up, but [here](https://github.com/earthtone/trivial-bankai-example) is a trivial example I've been using to play around with Bankai. As I mentioned, it most likely is some issue with my configuration/code, due to me not entirely understanding some of the opinions/presumptions of the tool.

My hope is to use Bankai as a build tool in some existing projects that use yo-yo, without having to re-write them for choo. Thanks for the help.

**Comment by goto-bus-stop** [comment]
Ahhh I see. app.js and router.js are cyclical dependencies of each other, and browser-pack-flat is not initialising the entry point correctly if it is in a cyclical chain.

just published browser-pack-flat@3.0.8 which should fix this; could you `npm update` and give it a shot?

**Comment by earthtone** [comment]
This did the trick! Thanks.

How common/uncommon are cyclical dependencies? It was quick hack on my part just to separate functionality into separate files to make things easier on me, but is it something that's generally advised against?

**Comment by goto-bus-stop** [comment]
Imo avoiding cyclical dependencies makes it easier to think about the order in which modules are executed; with cyclical `require()` calls you can get access to a module that has only executed half of its code, which can be confusing. Sometimes they are necessary tho so it's not a strict rule.
