### ISSUE TITLE
🔦Does b.ignore('sheetify/insert') not work?

### ISSUE THREAD

**Issue by ZhouHansen** [choojs/bankai#481]
I see `b.ignore('sheetify/insert')` in graph-script.js. But I can still use `sheetify/insert` module.
```js
var insertCss = require('sheetify/insert')
insertCss('body { background:blue; }')
```
Then the background of body turns to blue.

Further more, why ignore `sheetify/insert` module?

**Comment by goto-bus-stop** [comment]
`sheetify/insert` calls are [processed by `css-extract`](https://github.com/stackcss/css-extract/blob/master/index.js#L47-L50), so those require calls are removed. the `body { background:blue; }` stuff ends up in the `bundle.css` file instead.

sheetify/insert is `.ignore()`d because otherwise, it would still be included in the bundle, even though all calls to it were removed by css-extract
